import 'package:flutter/material.dart';

/// Resolves a lucide-react icon name (as stored in category/bucket data,
/// mirroring src/components/Icon.tsx) to a Material icon. Falls back to
/// a generic tag icon, matching the React fallback behaviour.
IconData lucideIcon(String name) {
  return _map[name] ?? Icons.sell_outlined;
}

const _map = <String, IconData>{
  'ShoppingCart': Icons.shopping_cart_outlined,
  'Utensils': Icons.restaurant_outlined,
  'Fuel': Icons.local_gas_station_outlined,
  'Car': Icons.directions_car_outlined,
  'ShoppingBag': Icons.shopping_bag_outlined,
  'Film': Icons.local_movies_outlined,
  'Stethoscope': Icons.medical_services_outlined,
  'Dumbbell': Icons.fitness_center_outlined,
  'Sparkles': Icons.auto_awesome_outlined,
  'PawPrint': Icons.pets_outlined,
  'HandHeart': Icons.volunteer_activism_outlined,
  'Zap': Icons.bolt_outlined,
  'Droplets': Icons.water_drop_outlined,
  'Flame': Icons.local_fire_department_outlined,
  'Wifi': Icons.wifi,
  'Smartphone': Icons.smartphone_outlined,
  'Tv': Icons.tv_outlined,
  'Newspaper': Icons.newspaper_outlined,
  'Home': Icons.home_outlined,
  'Building2': Icons.apartment_outlined,
  'Wrench': Icons.build_outlined,
  'Sofa': Icons.chair_outlined,
  'GraduationCap': Icons.school_outlined,
  'Baby': Icons.child_friendly_outlined,
  'HeartHandshake': Icons.volunteer_activism_outlined,
  'ShieldCheck': Icons.verified_user_outlined,
  'Gift': Icons.card_giftcard_outlined,
  'Plane': Icons.flight_outlined,
  'TrendingUp': Icons.trending_up,
  'LineChart': Icons.show_chart,
  'Sprout': Icons.eco_outlined,
  'BarChart3': Icons.bar_chart_outlined,
  'CandlestickChart': Icons.candlestick_chart_outlined,
  'PiggyBank': Icons.savings_outlined,
  'Repeat2': Icons.repeat_outlined,
  'Landmark': Icons.account_balance_outlined,
  'Briefcase': Icons.work_outline,
  'Umbrella': Icons.beach_access_outlined,
  'FileBadge': Icons.badge_outlined,
  'Coins': Icons.monetization_on_outlined,
  'Bitcoin': Icons.currency_bitcoin,
  'Building': Icons.business_outlined,
  'Bike': Icons.pedal_bike_outlined,
  'Wallet': Icons.account_balance_wallet_outlined,
  'Clock': Icons.access_time_outlined,
  'CreditCard': Icons.credit_card_outlined,
  'Tv2': Icons.live_tv_outlined,
  'Music': Icons.music_note_outlined,
  'Cloud': Icons.cloud_outlined,
  'AppWindow': Icons.window_outlined,
  'Gamepad2': Icons.sports_esports_outlined,
  'BookOpen': Icons.menu_book_outlined,
  'Cake': Icons.cake_outlined,
  'Heart': Icons.favorite_outline,
  'PartyPopper': Icons.celebration_outlined,
  'Flower2': Icons.local_florist_outlined,
  'Church': Icons.church_outlined,
  'Bot': Icons.smart_toy_outlined,
  'Receipt': Icons.receipt_long_outlined,
  'Tag': Icons.sell_outlined,
  'Repeat': Icons.repeat,
  'BadgePercent': Icons.percent,
  'Calendar': Icons.calendar_today_outlined,
  'Calculator': Icons.calculate_outlined,
};
