// PLACEHOLDER — generated by hand to match the shape of FlutterFire CLI
// output, NOT a real Firebase project. The values below will not connect
// to any real Firebase backend; they only let the app compile and run with
// FCM/Firebase disabled gracefully (see NotificationsService.init in
// lib/core/notifications/notifications_service.dart, which catches the
// init failure and no-ops instead of crashing the app).
//
// To wire up real push notifications:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. dart pub global activate flutterfire_cli
//   3. flutterfire configure --project=<your-firebase-project-id>
//   4. This file gets overwritten with real values, and
//      android/app/google-services.json + ios/Runner/GoogleService-Info.plist
//      get created automatically.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('FirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'moneypilot-placeholder',
    storageBucket: 'moneypilot-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE_OUTPUT',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'moneypilot-placeholder',
    storageBucket: 'moneypilot-placeholder.appspot.com',
    iosBundleId: 'io.moneypilot.app',
  );
}
